{{ if .Values.scale.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deployment
    name: {{ .Values.name }}
  minReplicas: {{ .Values.scale.min }}
  maxReplicas: {{ .Values.scale.max }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.scale.cpu }}
  - type: Resource
    resource:
      name: memory
      targetAverageValue: {{ .Values.scale.memory }}
{{ end }}
