{{- if gt .Values.pod.replicas 1.0 }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: {{ .Values.name }}
    chart: {{ template "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
      release: {{ .Release.Name }}
  minAvailable: {{ .Values.pod.minAvailable }}
{{- end }}
