{{ if .Values.global.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - {{ .Values.name }}
  http:
  - route:
    - destination:
        host: {{ .Values.name }}
    retries:
      attempts: {{ .Values.global.istio.retries }}
      perTryTimeout: 2s
{{ end }}
