name: name

global:
  pullSecrets: []
  pullPolicy: IfNotPresent
  # Rolling update via specific config hash
  # configHash: ""
  # priorityClassName: ""
  istio:
    enabled: false
    retries: 2

serviceAccount:
  create: false
  name: ""

image:
  repository: repo
  tag: latest
  digest: null

pod:
  replicas: 1
  minAvailable: 1
  annotations: {}
  # command: []

  # Mount config map volumes
  # configMap:
  #   name:
  #   path:
  extraConfigmapMounts: []
  # - name: certs-configmap
  #   mountPath: /etc/configmaps/
  #   subPath: subpath # (optional)
  #   configMap: example
  #   readOnly: true
  extraSecretMounts: []
  # - name: secret-files
  #   mountPath: /etc/secrets
  #   secretName: -secret-files
  #   defaultMode: 256 # (optional)
  #   readOnly: true

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
 limits:
   memory: 180M
 requests:
   memory: 180M
   cpu: 35m

healthCheck:
  port: ""
  path: /ping
  initialDelaySeconds: 3
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3


service:
  type: ClusterIP
  port: 80
  annotations: {}
  labels: {}

scale:
  enabled: false
  customMetrics: []
  min: 1
  max: 5
  cpu: 100
  memory: 80

metrics:
  enabled: false
  port: 9101
  targetPort: ""
  label: prometheus
  # serviceMonitor support for prometheus-operator
  serviceMonitor:
    enabled: false
    interval: 15s
    app:
      enabled: false
    envoy:
      port: 9102
      targetPort: 9102
      enabled: false

nodeSelector: {}

tolerations: []
  # - operator: Exists

affinity: {}
